### PR TITLE
Use Java 11 in default Docker images

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Use Java 11 in default Docker images

- Use Java 11 in default images
- Use AdoptOpenJDK 11.0.12 instead of 11.0.11
- Use AdoptOpenJDK 8u302 instead of 8u292

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by MarkEWaite** [comment]
@timja I found a surprise in the build.sh script while reading its console output on trusted.ci.jenkins.io.  I believe that the change I made in 6defb7d454caf1cb4339a201a52d83965529f51c and in 9c481247bb57baedcdf3a92b9f3cd4603616c07a is correct and complete, but would appreciate your review before it is merged.

I confirmed that the image built by the most recent run of the job is the image that is downloaded by `docker pull jenkins/agent:latest-buster-jdk11`.  I believe this is ready to merge but would like one more review before it is merged and I then monitor the build on trusted.ci.jenkins.io to confirm that it will publish the 4.10-1 tags using Java 11.

**Comment by timja** [comment]
> @timja I found a surprise in the build.sh script while reading its console output on trusted.ci.jenkins.io. I believe that the change I made in [6defb7d](https://github.com/jenkinsci/docker-agent/commit/6defb7d454caf1cb4339a201a52d83965529f51c) and in [9c48124](https://github.com/jenkinsci/docker-agent/commit/9c481247bb57baedcdf3a92b9f3cd4603616c07a) is correct and complete, but would appreciate your review before it is merged.
> 
> I confirmed that the image built by the most recent run of the job is the image that is downloaded by `docker pull jenkins/agent:latest-buster-jdk11`. I believe this is ready to merge but would like one more review before it is merged and I then monitor the build on trusted.ci.jenkins.io to confirm that it will publish the 4.10-1 tags using Java 11.

fix looks fine, although it should just have a `set -e` instead really but that can be done separately

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
If you hold off creating a release I'm going to file a PR to change to eclipse temurin

**Comment by MarkEWaite** [comment]
I think that the next release we'll see with this change will be 2.308 next Tuesday.  Thanks for merging and thanks for the change to Eclipse Temurin

**Comment by timja** [comment]
> I think that the next release we'll see with this change will be 2.308 next Tuesday. Thanks for merging and thanks for the change to Eclipse Temurin

These releases are tied to remoting versions nothing to do with core. 4.10 just needs to be tagged when we are ready

**Comment by MarkEWaite** [comment]
> These releases are tied to remoting versions nothing to do with core. 4.10 just needs to be tagged when we are ready

Thanks.  Had lost context  that this is the agent repository, not the controller repository.

I'm out of office next week (sorry for the poor timing, family trip into the mountains of Utah).  Would love to have 4.10 tagged and released today so that I could do some additional testing.  I've never done a release of the docker agent image.  There is a video from Oleg that describes the process, but I'd need to watch it.  Are you OK if I attempt to do a release?

**Comment by timja** [comment]
Fine by me but I think https://github.com/jenkinsci/docker-agent/pull/186 should be included in the release

enjoy your holiday

**Pull request merged**
