### PR TITLE
chore(updatecli) remove reference to a deleted file for Alpine

### PR DESCRIPTION
**Pull request by dduportal**
Quick hotfix of #521 to correct the `updatecli` process which is failing on the `master` branch

### CODE REVIEW

**Comment by dduportal** [comment]
Self-merging as:

- Updatecli process is fixed:

```
Run Summary
===========
Pipeline(s) run:
  * Changed:	0
  * Failed:	0
  * Skipped:	3
  * Succeeded:	5
  * Total:	8
```

- No functional change

**Comment by hervelemeur** [comment]
This manifest needs more work, will take a look later.

**Comment by lemeurherve** [comment]
Needs something like https://github.com/jenkinsci/docker-inbound-agent/pull/437

**Comment by lemeurherve** [comment]
Addressed in https://github.com/jenkinsci/docker-agent/pull/536

**Pull request merged**
