### PR TITLE
Upgrade remoting to 4.11.2

### PR DESCRIPTION
**Pull request by Hellspam**
Upgrade remoting to 4.11.2

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by Hellspam** [comment]
Do these also need to be changed?
https://github.com/jenkinsci/docker-agent/blob/master/build.sh#L10
https://github.com/jenkinsci/docker-agent/blob/master/build.ps1#L7
https://github.com/Hellspam/docker-agent/blob/master/docker-bake.hcl#L36

**Comment by timja** [comment]
No they are defaults and are intentionally set to old versions I think you may have only needed to change the props file but updating the rest does no harm

**Comment by Hellspam** [comment]
👍

**Comment by Hellspam** [comment]
When will a new release be cut?

**Pull request merged**
