### PR TITLE
Feat: Ensure that we have Windows images for both nanoserver and servercore, on Adoptium's JDK8,JDK11 and JDK17 [INFRA-3047]

### PR DESCRIPTION
**Pull request by dduportal**
This PR introduces the following changes:

- Ensure that all the existing Windows images are using Adoptium (Eclipse Temurin)
- Add the new JDK17 Windows images
- Ensure that each Windows images exists for all JDKs (8, 11 and 17) with a nanoserver and a windows server core each
- Improve the Windows Build step's performance by using docker-compose (and a `build-windows.yaml` docker-compose file) for parallel building the Windows images

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
~- [ ] Link to relevant issues in GitHub or Jira~
~- [ ] Link to relevant pull requests, esp. upstream and downstream changes~
~- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue~

### CODE REVIEW

**Comment by dduportal** [comment]
One of the modified images is failing to build. I'll check later.

**Comment by dduportal** [comment]
A few discoveries while working on this:

- All the nanoserver images can be derived from the windowsservercore easily (that would avoid the slow download part where we re-download the same git, git-lfs, remoting.jar...). That could be a nice improvement to ensure the windows images does not diverge over time
- I'm trying to use docker-compose to have a centralized manifest for the windows images (wip). It would also greatly accelerate the build time since `docker-compose build` accepts a `--parallel` flag :)
- I need to work on tests

**Comment by dduportal** [comment]
> Do we need that legacy build step?

We could remove it, but it would side-track the work here: we would have to update the `build.ps1` script to ensure that the docker image name from docker-compose's build are passed to tests.
Since it also manages the tags, I would prefer keeping the existing for now (in favor for a separated change of the script later) to not break builds on trusted.ci

**Comment by timja** [comment]
Tests are failing on windows on trusted CI: https://trusted.ci.jenkins.io:1443/blue/organizations/jenkins/Containers%2Fdocker%2Fdocker-agent/detail/4.10-7/2/pipeline

**Comment by timja** [comment]
Weird errors occurring when publishing the next version:
https://trusted.ci.jenkins.io:1443/blue/organizations/jenkins/Containers%2Fdocker%2Fdocker-agent/detail/4.11-1/2/pipeline/9

```

[2021-10-16T16:56:07.279Z] docker-compose version 1.29.2, build 5becea4c

[2021-10-16T16:56:07.279Z] BUILD: Starting Docker Compose General Build

[2021-10-16T16:56:08.668Z] powershell.exe : Flag '--parallel' is ignored when building with COMPOSE_DOCKER_CLI_BUILD=1

[2021-10-16T16:56:08.668Z] At C:\Jenkins\workspace\iners_docker_docker-agent_4.11-1@tmp\durable-9f6b78b3\powershellWrapper.ps1:3 char:1

[2021-10-16T16:56:08.668Z] + & powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -Comm ...

[2021-10-16T16:56:08.668Z] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[2021-10-16T16:56:08.668Z]     + CategoryInfo          : NotSpecified: (Flag '--paralle...KER_CLI_BUILD=1:String) [], RemoteException

[2021-10-16T16:56:08.668Z]     + FullyQualifiedErrorId : NativeCommandError
```

and

```
2021-10-16T17:03:42.911Z] x509: certificate signed by unknown authority
```

all over the place =/

**Comment by timja** [comment]
Passed on the third attempt

**Pull request merged**
