### PR TITLE
Upgrade Remoting to 4.9

### PR DESCRIPTION
**Pull request by agentgonzo**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Follow on from #175

### CODE REVIEW

**Comment by agentgonzo** [comment]
Build failure, presumably infra-related:
```
[2021-06-24T10:41:11.925Z] Cannot contact EC2 (aws) - Windows 2019 (i-00359c6e948511869): hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@416279d1:EC2 (aws) - Windows 2019 (i-00359c6e948511869)": Remote call on EC2 (aws) - Windows 2019 (i-00359c6e948511869) failed. The channel is closing down or has closed down
```
Can someone retrigger the build please and see if it passes this time?

**Comment by MarkEWaite** [comment]
> Can someone retrigger the build please and see if it passes this time?

Launched a new build

**Comment by agentgonzo** [comment]
@slide - thanks for merging. Do you know what extra is needed to generate these images with a 4.9 tag? I can see that the CI built 
the `jenkins4eval/agent` image from this repo, but I don't know how that gets turned into `jenkins/agent`. The highest tagged version is 4.7-1 (that is used in [docker-inbound-agent](https://github.com/jenkinsci/docker-inbound-agent/search?q=4.7-1).

What I'm ultimately after is a version of `jenkins/jnlp-agent-maven` that contains version 4.9 of the remoting jar.

**Comment by slide** [comment]
I need to login to the secure CI and launch a build for that tag. I'll do that today

**Comment by agentgonzo** [comment]
Ok, thanks. One that is done I'll update the inbound agents with a pr. Either over the weekend or on Monday

**Comment by agentgonzo** [comment]
@slide did you release the 4.9 image?

**Comment by slide** [comment]
Yes, I just did. The image should be pushed in the next hour or so to dockerhub

**Pull request merged**
