### PR TITLE
Remove Java 11 support

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Remove Java 11 support

Jenkins weekly 2.463 dropped support for Java 11. Jenkins LTS 2.479.1 will drop support for Java 11 when it releases 30 Oct 2024.

The Jenkins security team only provides security fixes for the most recent weekly release and the most recent LTS release. That means there will be no security updates for Jenkins LTS versions prior to 2.479.1 once it is released 30 Oct 2024.

Jenkins agents require a JDK that has the same major version as the controller or a greater JDK major version than the controller JVM. After 30 Oct 2024, there will be no supported configuration where Java 11 agents run. This change removes the Java 11 build and update process.

We can wait until 30 Oct 2024 to merge this change if needed, but there is not much reason to wait beyond 30 Oct 2024 for that merge.

Accept case insensitive location in HTTP response.

No longer generates container images for:

* Alpine Linux JDK 11
* Arch Linux
* Debian JDK 11
* Windows Nanoserver JDK 11
* Windows Server Core JDK 11

### Testing done

Confirmed that automated build and test passes on my Linux computer.

Confirmed that no Java 11 container image is created after this change.

Recreated the output in the README based on latest changes.

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by gounthar — APPROVED** [review]
Thanks, Mark!
Unfortunately, my review does not count. 😉

**Review by timja — DISMISSED** [review]

**Review by timja — APPROVED** [review]

**Comment by MarkEWaite** [comment]
Question has been raised to the [platform SIG](https://matrix.to/#/!wYRZPxzhiQDTynnzVz:gitter.im/$6oqYedkMENAb5DHjCJmU6iC1l-Mpj5HApsNx_X_zLeM?via=gitter.im&via=matrix.org&via=matrix.freyachat.eu) for further discussion on the timing of this change.  I think we should merge it next week, but am open to further discussion.

**Review by lemeurherve — APPROVED** [review]
👏

**Comment by MarkEWaite** [comment]
Plan as agreed in [Platform SIG meeting](https://community.jenkins.io/t/platform-sig-october-08-2024/21600) is to merge this early next week

**Pull request merged**
