### PR TITLE
Bumping the baseline debian docker baseline bookworm image to bookworm-20240211

### PR DESCRIPTION
**Pull request by mikenau**
Upgrading the baseline debian version to bookworm-20240211. The existing version `bookworm-20240110` is not compatible with FIPS enabled runtimes and any apt-get commands fail with
```
Reading package lists...fatal error in libgcrypt, file ../../src/misc.c, line 92, function _gcry_fatal_error: requested algo not in md context
Fatal error: requested algo not in md context
```

### Testing done

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Review by gounthar — APPROVED** [review]
Looks good to me.
I guess we have a problem with the updatecli manifest, this change should have been proposed earlier by the updatecli action. 🤷

**Comment by gounthar** [comment]
My bad, we're not tracking Debian version with `updatecli` yet. 😨 
I'll create a PR for that. 🤷

**Comment by mikenau** [comment]
Thanks everyone. @lemeurherve @gounthar - When can I expect to see the official inbound-agent docker image updated with this change at https://hub.docker.com/r/jenkins/inbound-agent/tags?

**Comment by lemeurherve** [comment]
@mikenau I've created a new release https://github.com/jenkinsci/docker-agent/releases/tag/3206.vb_15dcf73f6a_9-5, they are now available.

**Comment by mikenau** [comment]
> @mikenau I've created a new release https://github.com/jenkinsci/docker-agent/releases/tag/3206.vb_15dcf73f6a_9-5, they are now available.

Thank you 👍

**Pull request merged**
