### PR TITLE
Build jenkins-agent image with ltsc2022 and jdk11 

### PR DESCRIPTION
**Pull request by khatrig**
**Build jenkins-agent image with ltsc2022 + jdk11**

### CODE REVIEW

**Comment by MarkEWaite** [comment]
Do Windows Docker images still require precise matching between the operating system kernel and the Docker image?  In other words, does this pull request mean that we need to include Windows Server 2022 in the Jenkins infrastructure before it can be considered?

**Comment by khatrig** [comment]
> 

Yes and Yes. I assume you are referring to this - https://github.com/containerd/containerd/issues/6508

**Comment by khatrig** [comment]
Seems the build failed due to this -
https://ci.jenkins.io/blue/organizations/jenkins/Packaging%2Fdocker-agent/detail/PR-238/1/pipeline#step-27-log-1577

`no matching manifest for windows/amd64 10.0.17763 in the manifest list entries
`

**Comment by timja** [comment]
Could you create a helpdesk ticket for it: https://github.com/jenkins-infra/helpdesk

**Comment by jglick** [comment]
https://github.com/jenkins-infra/helpdesk/issues/2629 now?

**Comment by dduportal** [comment]
The support of Windows 2022 is there on the infra. You have to define a new node, in the pipeline, with the label `windows-2022` for this.

**Comment by dduportal** [comment]
Ping @khatrig are you still ok to work on this PR?

**Comment by dduportal** [comment]
I'm closing this PR as no feedback from the author since January + duplicate of #441 .

Another contributor did implement the Windows Server 2022 in #441 instead.


Anyway, many thanks for raising the subject and trying to bring it up! It was a collective effort from the whole communit!

**Pull request closed without merging**
