### PR TITLE
feat(updatecli): Track UBI9 version

### PR DESCRIPTION
**Pull request by gounthar**
After [@lemeurherve's work](https://github.com/jenkinsci/docker-agent/pull/880) on the `updatecli` manifest to keep UBI9 updated in the docker bake file and Dockerfile, it became clear something wasn't working as expected when trying to find the latest version of the UBI9 container with the default `updatecli` behavior.  

I then took Hervé's manifest and transitioned it into using a shell script to find the "right" version.  
I discovered a [Swagger description](https://catalog.redhat.com/api/containers/v1/ui/#/Repositories/graphql.images.get_images_by_repo) that led me to the correct API endpoint.  
This endpoint allowed me to query the `ubi9` containers, sorted by the last update date and filtered by the `latest` tag.  
As a result, I obtained the version `9.4-1214.1726694543`.  

The script works as is but would need some additional refinement to return a list of versions rather than just the most recent one.

This could help partially solve #883.

### Testing Done

I updated my local configuration to target my fork instead of upstream.  
To test the changes, I intentionally kept my master branch out-of-date, and `updatecli` successfully created [this PR](https://github.com/gounthar/docker-agent/pull/1) for me.

The command used for testing:  
`updatecli diff --debug --config ./updatecli/updatecli.d/rhel-ubi9.yaml --values ./updatecli/values.github-action.yaml 2>&1`

### Submitter checklist
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- ~~Link to relevant issues in GitHub or Jira~~
- [X] Link to relevant pull requests, esp. upstream and downstream changes
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by timja — COMMENTED** [review]
this seems a bit over complicated, does renovate or dependabot do this correctly and simpler?

**Comment by gounthar** [comment]
I think dependabot handles the version retrieval pretty well, but I'm not sure it can update the docker bake file.

**Comment by timja** [comment]
> I think dependabot handles the version retrieval pretty well, but I'm not sure it can update the docker bake file.

renovate would be able to with the regex method pretty easily then in the bake file

**Comment by dduportal** [comment]
Please note that this "issue" should be temporarily and updatecli should be fixed

**Comment by lemeurherve** [comment]
This PR added a renamed version of ./updatecli/scripts/ubi9-tags.sh (introduced in https://github.com/jenkinsci/docker-agent/pull/901) named ./updatecli/scripts/ubi9-tags.sh, but didn't remove the original, now unused.

**Pull request merged**
