### PR TITLE
chore: jlink improvements from jenkinsci/docker

### PR DESCRIPTION
**Pull request by lemeurherve**
This PR integrates jlink improvement from https://github.com/jenkinsci/docker/pull/1857.

> adapted it to be POSIX compliant as the Alpine ash shell doesn't support arrays

Notes:
- I removed the TARGETPLATFORM check in Alpine images as we're not publishing any arm/v7 image of this kind.
- The Debian "preview" Dockerfile doesn't need these changes as it's used to build only one JDK (21).

Extracted from:
- https://github.com/jenkinsci/docker-agent/pull/786

### Testing done

Local builds + CI

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]

**Comment by dduportal** [comment]
> I removed the TARGETPLATFORM check in Alpine images as we're not publishing any arm/v7 image of this kind.

That assertion is false as per https://github.com/jenkinsci/docker-agent/blob/6d7bd6b71460c10571ff628052d10fd726abfbe3/docker-bake.hcl#L248

We *do* publish `arm/v7` images for the agents. However, the builds seems to have passed! 
Anyone with a 32 bits ARM to test (ping @gounthar as you have my Rpis ;) ) the resulting image? It would be really a good news if no need for this `if` anymore \o/

**Comment by lemeurherve** [comment]
> > I removed the TARGETPLATFORM check in Alpine images as we're not publishing any arm/v7 image of this kind.
> 
> That assertion is false as per
> 
> https://github.com/jenkinsci/docker-agent/blob/6d7bd6b71460c10571ff628052d10fd726abfbe3/docker-bake.hcl#L248
> 
> We _do_ publish `arm/v7` images for the agents. However, the builds seems to have passed! Anyone with a 32 bits ARM to test (ping @gounthar as you have my Rpis ;) ) the resulting image? It would be really a good news if no need for this `if` anymore \o/

This line concerns debian images, not the Alpine one.

None of the Alpine images specify arm/v7 architecture:
https://github.com/jenkinsci/docker-agent/blob/6d7bd6b71460c10571ff628052d10fd726abfbe3/docker-bake.hcl#L171-L225

**Comment by dduportal** [comment]
> > > I removed the TARGETPLATFORM check in Alpine images as we're not publishing any arm/v7 image of this kind.
> > 
> > 
> > That assertion is false as per
> > https://github.com/jenkinsci/docker-agent/blob/6d7bd6b71460c10571ff628052d10fd726abfbe3/docker-bake.hcl#L248
> > 
> > We _do_ publish `arm/v7` images for the agents. However, the builds seems to have passed! Anyone with a 32 bits ARM to test (ping @gounthar as you have my Rpis ;) ) the resulting image? It would be really a good news if no need for this `if` anymore \o/
> 
> @dduportal This line concerns debian images, not the Alpine one.
> 
> None of the Alpine images specify arm/v7 architecture, AFAICT the assertion is true:
> 
> https://github.com/jenkinsci/docker-agent/blob/6d7bd6b71460c10571ff628052d10fd726abfbe3/docker-bake.hcl#L171-L225

🤦 I missed the `Alpine£ word in the original sentence. my apologies.

**Comment by dduportal** [comment]
> @dduportal let me know if I should send back your Pis soon. 😉

Thanks for taking some time. The goal was to test the unreleased version but as underlined by Hervé above I was misguided: there are no arm/v7 Alpine (I mistook with Debian).

**Comment by gounthar** [comment]
My bad, I misunderstood the request. 🤷

**Pull request merged**
